services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: ""
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: your_bot_token_here #заменить
      - key: WEBHOOK_URL
        value: https://your-service-name.onrender.com/webhook #заменить
