services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: ""
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: 7918963889:AAFJ0IZnP2GuCt1WBMoVg0qWgNXnJnYUQig
      - key: WEBHOOK_URL
        value: https://your-service-name.onrender.com/webhook #заменить
